# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "github.com/kevinburke/go-bindata",
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false
  unused-packages = false

[[prune.project]]
  name = "github.com/kevinburke/go-bindata"
  non-go = false
  unused-packages = false

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "=v0.2.0"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "v0.0.6"

[[constraint]]
  name = "github.com/openshift/api"
  revision = "21e40de482627b2047cbf430594540413539a442"

[[constraint]]
  name = "github.com/kevinburke/go-bindata"
  version = "v3.11.0"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.2"
