# This resource is not created by CVO, it is only used as a communication
# mechanism to tell the CVO which ClusterOperator resource to wait for.
# DNS operator creates and updates this resource.
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: dns
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
