apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-dns-operator
  namespace: openshift-cluster-dns-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-dns-operator
  template:
    metadata:
      labels:
        name: cluster-dns-operator
    spec:
      dnsPolicy: Default
      restartPolicy: Always
      containers:
        - name: cluster-dns-operator
          image: openshift/origin-cluster-dns-operator:latest
          command:
          - cluster-dns-operator
          imagePullPolicy: IfNotPresent
          terminationGracePeriodSeconds: 2
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "cluster-dns-operator"
            - name: IMAGE
              value: openshift/origin-coredns:v4.0
      serviceAccountName: cluster-dns-operator
      tolerations:
      - operator: Exists # dns operator should be schedulable always.
