# Binds the operator role to its Service Account.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dns-operator
  namespace: openshift-dns-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
subjects:
- kind: ServiceAccount
  name: dns-operator
  namespace: openshift-dns-operator
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: dns-operator
